---
sudo: false
language: ruby
bundler_args: --without development system_tests
rvm:
  - 2.2.7
  - 2.3.3
script: RAKE_ENV=ci bundle exec rake test
cache:
  - bundler
  - directories:
    - $HOME/librarian-puppet
env:
  matrix:
    - PUPPET_VERSION="~> 4.5.0" STRICT_VARIABLES=yes
    - PUPPET_VERSION="~> 4.6.0" STRICT_VARIABLES=yes
    - PUPPET_VERSION="~> 4.7.0" STRICT_VARIABLES=yes
    - PUPPET_VERSION="~> 4.8.0" STRICT_VARIABLES=yes
    - PUPPET_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
    - PUPPET_VERSION="~> 4.10.0" STRICT_VARIABLES=yes
    - PUPPET_VERSION="~> 5.0.0" STRICT_VARIABLES=yes
