HOSTS:
  debian-9-x64:
    platform: debian-9-amd64
    hypervisor : docker
    image: deric/stretch-puppet:5.5.14
    roles:
      - agent
    debug: true
CONFIG:
  masterless: true
  log_level: info
  type: foss